SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE
FROM MEMBER;

INSERT INTO MEMBER(NAME, USERID, PWD, EMAIL, PHONE, ADMIN)
VALUES('박규영', 'parkgy', '1234', 'pgy@gmail.com', '010-1111-2222', 0);

SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE
FROM MEMBER
WHERE USERID = 'parkgy';

UPDATE MEMBER
SET NAME = '문채원', PWD = '5678', EMAIL='mcw@gmail.com', PHONE = '010-3333-5555', ADMIN=1, JOINDATE='2020-08-20'
WHERE USERID = 'parkgy';

DELETE MEMBER
WHERE USERID = 'banana';

SELECT PWD FROM MEMBER WHERE USERID = 'somi';

SELECT * FROM MEMBER;

SELECT NAME, USERID, EMAIL, PHONE, ADMIN, JOINDATE
FROM MEMBER
WHERE USERID = 'somi' AND PWD = '1111';

SELECT *
FROM user_tables;

SELECT TITLE_NO, TITLE_NAME FROM title;
DELETE title WHERE title_no = 6;

SELECT * FROM department;
DELETE FROM department WHERE dept_no = 0;

SELECT * FROM DEPARTMENT d ;

CREATE OR REPLACE VIEW VW_EMPLOYEEJOIN
AS
SELECT e.EMP_NO, e.EMP_NAME, e.TNO, e.MANAGER, e.SALARY, e.DNO, e.REGDATE, e.EMAIL, e.TEL, e.PIC_URL, TITLE_NAME, DEPT_NAME, FLOOR, m.EMP_NAME AS MANAGER_NAME
FROM EMPLOYEE e JOIN TITLE t ON e.TNO = t.TITLE_NO
	LEFT JOIN EMPLOYEE m ON e.MANAGER = m.EMP_NO
	JOIN DEPARTMENT d ON e.DNO = d.DEPT_NO;

SELECT * FROM VW_EMPLOYEEJOIN;

SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD, REGDATE, TEL, PIC_URL FROM EMPLOYEE;

SELECT * FROM product;

ALTER TABLE PRODUCT 
RENAME COLUMN descritpion TO description;
